import java.util.Vector;

import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Groarq-lap
 */
public class LibraryForm extends javax.swing.JFrame {
	private Library library;
    /**
     * Creates new form LibraryForm
     */
    public LibraryForm() {
    	library = new Library();
    	library.load();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loanBookField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loanSurnameField = new javax.swing.JTextField();
        consoleLoans = new javax.swing.JTextField();
        addLoan = new javax.swing.JButton();
        removeLoanButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        removeLoanIdField = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bookAuthorField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        magazineNumberField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newspaperNumberField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bookTitleField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        magazineTitleField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        newspaperTitleField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addMagazineButton = new javax.swing.JButton();
        addNewspaperButton = new javax.swing.JButton();
        addBookButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        consoleBooks = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        readerNameField = new javax.swing.JTextField();
        readerSurnameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addReaderButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        consoleReader = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setName("separator"); // NOI18N
       
        booksList.setModel(setBooksTable()); 
        jScrollPane1.setViewportView(booksList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Książki", jPanel1);

        jTable1.setModel(setReadersTable());
        
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("Czytelnicy", jPanel2);

        jTabbedPane1.addTab("Listy", jTabbedPane6);

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 51, 0));
        jSeparator1.setEnabled(false);
        jTabbedPane1.addTab("", jSeparator1);

        jLabel1.setText("id książki");

        loanBookField.setName(""); // NOI18N

        jLabel2.setText("nazwisko");

        consoleLoans.setEditable(false);
        consoleLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleLoansActionPerformed(evt);
            }
        });

        addLoan.setText("Wypożycz");
        addLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoanActionPerformed(evt);
            }
        });

        removeLoanButton.setText("Oddaj");
        removeLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLoanButtonActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(removeLoanIdField);

        jLabel3.setText("id książki");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(consoleLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(loanSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addLoan))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeLoanButton))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(35, 35, 35)
                            .addComponent(loanBookField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(107, 107, 107)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 214, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(loanBookField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLoan)
                    .addComponent(removeLoanButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(consoleLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jTabbedPane5.addTab("Wypożycz/Oddaj", jPanel3);

        bookAuthorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAuthorFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("autor");

        jLabel5.setText("numer");

        newspaperNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspaperNumberFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("numer");

        jLabel7.setText("tytuł");

        magazineTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magazineTitleFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("tytuł");

        jLabel9.setText("tytuł");

        addMagazineButton.setText("Dodaj magazyn");
        addMagazineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMagazineButtonActionPerformed(evt);
            }
        });

        addNewspaperButton.setText("Dodaj gazetę");
        addNewspaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewspaperButtonActionPerformed(evt);
            }
        });

        addBookButton.setText("Dodaj Książkę");
        addBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookButtonMouseClicked(evt);
            }
        });
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        consoleBooks.setEditable(false);
        consoleBooks.setColumns(20);
        consoleBooks.setRows(5);
        jScrollPane3.setViewportView(consoleBooks);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(addBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookAuthorField)
                    .addComponent(bookTitleField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(addMagazineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(magazineTitleField)
                    .addComponent(magazineNumberField))
                .addGap(204, 204, 204)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addNewspaperButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newspaperTitleField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newspaperNumberField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(magazineNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newspaperNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(magazineTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newspaperTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookButton)
                    .addComponent(addMagazineButton)
                    .addComponent(addNewspaperButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jTabbedPane5.addTab("Dodaj książkę", jPanel4);

        readerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerNameFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Imie");

        jLabel11.setText("Nazwisko");

        addReaderButton.setText("Dodaj czytelnika");
        addReaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReaderButtonActionPerformed(evt);
            }
        });

        consoleReader.setEditable(false);
        consoleReader.setColumns(20);
        consoleReader.setRows(5);
        jScrollPane4.setViewportView(consoleReader);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(readerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(readerSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(addReaderButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 375, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readerSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(addReaderButton)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Dodaj czytelnika", jPanel5);

        jTabbedPane1.addTab("Akcje", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("bookListTab");

        pack();
    }// </editor-fold>                        

    private void addReaderButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	library.createReader(new Reader(readerNameField.getText(), readerSurnameField.getText()));
    	consoleReader.setText("Dodano czytelnika!");
    	jTable1.setModel(setReadersTable());
    	library.save();
    }                                               

    private void magazineTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void newspaperNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void bookAuthorFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void readerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void consoleLoansActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void addBookButtonMouseClicked(java.awt.event.MouseEvent evt) {   
    	try{
    	library.createVolume(new Book(bookAuthorField.getText(), bookTitleField.getText()));
    	}catch(Exception e) {
    		consoleBooks.setText("Błąd");
    	}
    	consoleBooks.setText("Dodano książkę!");
    	bookAuthorField.setText("");
    	bookTitleField.setText("");
    	booksList.setModel(setBooksTable());
    	library.save();
    }                                          

    private void addLoanActionPerformed(java.awt.event.ActionEvent evt) {  
    	 Volume volume = library.findVolume(loanBookField.getText());
         Reader reader = library.findReader(loanSurnameField.getText());
         if(volume == null || reader == null){
        	 consoleLoans.setText("Błędne dane.");
        	 return;
         }
         if(library.addVolumeToReader(volume, reader) == true) {
        	 consoleLoans.setText("Wypożyczono książkę!");
        	 loanBookField.setText("");
        	 loanSurnameField.setText("");
        	 booksList.setModel(setBooksTable());
        	 jTable1.setModel(setReadersTable());
        	 library.save();
         }
         else consoleLoans.setText("Błąd! Czytelnik ma zbyt dużo książek.");
    }                                       

    private void removeLoanButtonActionPerformed(java.awt.event.ActionEvent evt) { 
    	Volume volume = library.findVolume(removeLoanIdField.getText());
    	if(volume == null){
       	 consoleLoans.setText("Błędne dane.");
       	 return;
        }
    	if(library.removeVolumeFromOwner(volume)== true){
    		consoleLoans.setText("Usunięto wypożyczenie");
    		booksList.setModel(setBooksTable());
    		jTable1.setModel(setReadersTable());
    		library.save();
    	}else consoleLoans.setText("Błąd!");
    }                                                

    private void addMagazineButtonActionPerformed(java.awt.event.ActionEvent evt) { 
    	try{
    	library.createVolume(new Magazine(magazineTitleField.getText(), Integer.parseInt(magazineNumberField.getText())));
    	}catch(Exception e) {
    		consoleBooks.setText("Błąd");
    	}
    	consoleBooks.setText("Dodano czasopismo!");
    	magazineTitleField.setText("");
    	magazineNumberField.setText("");
    	booksList.setModel(setBooksTable());
    	library.save();
    }                                                 

    private void addNewspaperButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	try{
    	library.createVolume(new NewsPaper(newspaperTitleField.getText(), Integer.parseInt(newspaperNumberField.getText())));
    	}catch(Exception e) {
    		consoleBooks.setText("Błąd");
    	}
    	consoleBooks.setText("Dodano gazetę!");
    	newspaperTitleField.setText("");
    	newspaperNumberField.setText("");
    	booksList.setModel(setBooksTable());
    	library.save();
    } 
    
    private DefaultTableModel setBooksTable(){
    	 int columnCount = 4;
         Vector data = new Vector(columnCount);
         Vector row = new Vector(columnCount);
         Vector columnNames = new Vector(columnCount);

        columnNames.addElement("id");
        columnNames.addElement("nazwa");
        columnNames.addElement("autor/numer");
        columnNames.addElement("dostępność");
        int i = 0;
        while (i < library.getVolumes().size()) {
             row.addElement(library.getVolumes().get(i).getUniqueId());
             row.addElement(library.getVolumes().get(i).getName());
             
             if(library.getVolumes().get(i).getClass().equals(Book.class)) {
             	row.addElement(library.getVolumes().get(i).getAuthor());	
             }else {row.addElement(library.getVolumes().get(i).getNumber());}
             
             row.addElement(library.getVolumes().get(i).checkAvailability());
             i++;
             data.addElement(row);
             row = new Vector(columnCount); // Create a new row Vector
         }
         DefaultTableModel model = new DefaultTableModel(data, columnNames);  
         return model;
    }
    
    private DefaultTableModel setReadersTable(){
   	 int columnCount = 5;
        Vector data = new Vector(columnCount);
        Vector row = new Vector(columnCount);
        Vector columnNames = new Vector(columnCount);

       columnNames.addElement("id");
       columnNames.addElement("imie");
       columnNames.addElement("nazwisko");
       columnNames.addElement("ilosc ksiazek");
       columnNames.addElement("kara");
       int i = 0;
       while (i < library.getReaders().size()) {
            row.addElement(library.getReaders().get(i).getId());
            row.addElement(library.getReaders().get(i).getName());
            row.addElement(library.getReaders().get(i).getSurname());
            row.addElement(library.getReaders().get(i).getLoaned().size());
            row.addElement(library.getReaders().get(i).getPenalty());
            i++;
            data.addElement(row);
            row = new Vector(columnCount); // Create a new row Vector
        }
        DefaultTableModel model = new DefaultTableModel(data, columnNames);  
        return model;
   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addLoan;
    private javax.swing.JButton addMagazineButton;
    private javax.swing.JButton addNewspaperButton;
    private javax.swing.JButton addReaderButton;
    private javax.swing.JTextField bookAuthorField;
    private javax.swing.JTextField bookTitleField;
    private javax.swing.JTable booksList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea consoleBooks;
    private javax.swing.JTextField consoleLoans;
    private javax.swing.JTextArea consoleReader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField loanBookField;
    private javax.swing.JTextField loanSurnameField;
    private javax.swing.JTextField magazineNumberField;
    private javax.swing.JTextField magazineTitleField;
    private javax.swing.JTextField newspaperNumberField;
    private javax.swing.JTextField newspaperTitleField;
    private javax.swing.JTextField readerNameField;
    private javax.swing.JTextField readerSurnameField;
    private javax.swing.JButton removeLoanButton;
    private javax.swing.JTextPane removeLoanIdField;
    // End of variables declaration                   
}
